/* src/include/config.h.  Generated by configure.  */
/* src/include/config.h.in.  Generated from configure.ac by autoheader.  */

/* Whether __clear_cache is available */
/* #undef HAS_SYSTEM_CLEAR_CACHE */

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `getpagesize' function. */
#define HAVE_GETPAGESIZE 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have a working `mmap' system call. */
#define HAVE_MMAP 1

/* Define to 1 if you have the `munmap' function. */
#define HAVE_MUNMAP 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Whether __func__ is available */
/* #undef HAVE___func__ */

/* put "SableVM" in every object instance header */
/* #undef MAGIC */

/* turn off runtime assertions */
/* #undef NDEBUG */

/* Name of package */
#define PACKAGE "sablevm"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://sablevm.org/"

/* Define to the full name of this package. */
#define PACKAGE_NAME "sablevm"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "sablevm svm_partial_inlining+5723"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "sablevm"

/* Define to the version of this package. */
#define PACKAGE_VERSION "svm_partial_inlining+5723"

/* print statistics on VM exit */
/* #undef STATISTICS */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "svm_partial_inlining+5723"

/* link with POSIX library functions */
#define _POSIX_C_SOURCE 199506L

/* link with reentrant library functions */
#define _REENTRANT 1

/* bidirectional object layout */
#define _SABLEVM_BIDIRECTIONAL_OBJECT_LAYOUT 1

/* copying collector */
#define _SABLEVM_COPY_GC 1

/* direct threaded interpreter */
/* #undef _SABLEVM_DIRECT_THREADED_INTERPRETER */

/* generational copying collector */
/* #undef _SABLEVM_GENCOPY_GC */

/* siginfo_t is supported */
#define _SABLEVM_HAS_SIGINFO 1

/* turn on inlinability testing mode machinery */
/* #undef _SABLEVM_INLINABILITY_TESTING */

/* inlined threaded interpreter */
/* #undef _SABLEVM_INLINED_THREADED_INTERPRETER */

/* turn on memory tracking */
/* #undef _SABLEVM_MEMORY_DEBUGGING */

/* turn on possible dynamic method inlining */
#define _SABLEVM_METHOD_INLINING 1

/* turn on method inlining statistics */
/* #undef _SABLEVM_METHOD_INLINING_STATS */

/* no collector */
/* #undef _SABLEVM_NO_GC */

/* package name */
#define _SABLEVM_PACKAGE_NAME "sablevm"

/* package version */
#define _SABLEVM_PACKAGE_VERSION "svm_partial_inlining+5723"

/* Enable things we don't support well or don't want to support */
#define _SABLEVM_REAL_LIFE_BROKENNESS 1

/* use signals to detect exceptions */
/* #undef _SABLEVM_SIGNALS_FOR_EXCEPTIONS */

/* switch threaded interpreter */
#define _SABLEVM_SWITCH_THREADED_INTERPRETER 1

/* traditional object layout */
/* #undef _SABLEVM_TRADITIONAL_OBJECT_LAYOUT */

/* link with XOpen library functions */
#define _XOPEN_SOURCE 500

/* add common BSD extensions */
/* #undef _XPG4_2 */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* (do not) make internal functions static */
#define svm_static static
